### ISSUE TITLE
Please update submodule to latest release

### ISSUE THREAD

**Issue by RobVanGroenewoud** [nate-strauser/meteor-animate-css#3]
Apparently animate.css has gotten lots of performance improvements and additional effects since the latest submodule update of this Meteor package. I noticed it because I was looking for a basic slideInUp effect, which is not included in the current packaged version.

I'd rather not create a fork and publish an updated package separately, so it would be great if you could bump it to the most recent release (currently 3.2.5).

Thanks!

**Comment by RobVanGroenewoud** [comment]
Awesome, thanks for bumping!

**Comment by mbrookes** [comment]
Minor updates in the last month or two...

**Comment by nate-strauser** [comment]
bumped to 3.4.0

**Comment by mbrookes** [comment]
Thanks!
